sudo: required
language: python
python:
- '3.8'
addons:
  chrome: stable
install:
- pip install -r requirements.txt
script: pytest
before_script:
- wget https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.8.0/bin/
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
