language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: LA+QjV/AzOgoAeZKJRNZOx5wuHJkiUWGVUOcK+3AJyWowxE2mVAvIWHL7coB46dBoVGYTztz1DP1/KAY69SshIWitevCePTtnWRbEZjVQq24jOIJE/tMAcGuhNJ8HBes6MNyghHiKJIEValEbh+GpBSjM3xxlMWQDnmSJjNtLOo1CQuV2DkmVvOe20eX0uUacaqDCQR7Quzvf5wqVwxSx6QTvixZgguY+TkC4s2cD9bxybI3OiOrlQiPRGK1PzsuVtJg9GtWdRFPKTQf31FrjkEeMZseP4OfsM7Qzq3hwBlgmCgTk1fxmu7ZOB7gkZ6eHb12SZyqSM9Zz8bZQFVI+K6ssbvcBctlhIuhgZf+6zjCXWSKi13tZaTb76DQ7BhNiOOnCfaU93W6A+6L8XZybrjDTr7Dmyg6muoY2jrlKkkTcayj+gOkOlUm0JkfTvC24bHIJrNogo+22hG8rbsk0DQjjj8Yo3C8nfoE42dE+SnPLTlLD03LFcUg4puaInBsN1CTAFuKJfra6gB/H8zIzym3MST4Qnx9+xDnKGyA2dyOCvoh4xUJpsuOkakwTu3PXbzBMl/ps+d0brhU4hH/8ha9wjRsUEbEF69zaIpIxoKZLs0iFTuT0SiNmTJiBh8PfTm7H5L9KT2tjxUwu3Q7z6WcOY4mrhmMATxjVPdAhZ8=
  app: analogue-mercury
  strategy: git
